name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SSRFargateDockerLogin
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/ssrfargate .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/ssrfargate

      - name: download AWS
        run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

      - name: unzip AWS
        run: unzip awscliv2.zip

      - name: install AWS
        run: ./aws/install

      - name: set AWS key
        run: aws configure set aws_access_key_id AKIA4ARPVTO2IWF2IYPL

      - name: set AWS access
        run: aws configure set aws_secret_access_key uqpv5GckzNgqogUw0lO7TXkPN5xObGw9ZGoZ7XDj

      - name: set AWS region
        run: aws configure set default.region us-west-2

      - name: set AWS test
        run: aws configure set region us-west-2 --profile testing

      - name: Refresh Server
        run: python3 ECSManager.py
