name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SSRFargateDockerLogin
    steps:
      - name: set AWS key
        run: aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}

      - name: set AWS access
        run: aws configure set aws_secret_access_key ${{ secrets.AWS_ACCESS }}

      - name: set AWS region
        run: aws configure set default.region us-west-2

      - name: set AWS test
        run: aws configure set region us-west-2 --profile testing

      - uses: actions/checkout@v3
      - name: Refresh Server
        run: python3 ECSManager.py

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/ssrfargate . --build-arg aws_key="${{ secrets.AWS_KEY }}" --build-arg aws_secret="${{ secrets.AWS_ACCESS }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/ssrfargate

