name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SSRFargate
    steps:
      - name: set AWS key
        run: aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}

      - name: set AWS access
        run: aws configure set aws_secret_access_key ${{ secrets.AWS_ACCESS }}

      - name: set AWS region
        run: aws configure set default.region us-west-2

      - name: set AWS test
        run: aws configure set region us-west-2 --profile testing

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/ssrfargateqin .
            --build-arg aws_key="${{ secrets.AWS_KEY }}"
            --build-arg aws_secret="${{ secrets.AWS_ACCESS }}"
            --build-arg google_key="${{ secrets.GOOGLE_KEY }}"
            --build-arg google_secret="${{ secrets.GOOGLE_SECRET }}"
            --build-arg DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}"
            --build-arg CHATGPT_API_KEY="${{ secrets.CHATGPT_API_KEY }}"
            --build-arg rsa="${{ secrets.RSA }}"
            --build-arg rsa_public="${{ secrets.RSA_PUB }}"
            --build-arg V2RAY_CADDY_CONFIG="${{ vars.V2RAY_CADDY_CONFIG }}"
            --build-arg V2RAY_CADDYFILE="${{ vars.V2RAY_CADDYFILE }}"
            --build-arg V2RAY_DOWNLOADURL="${{ vars.V2RAY_DOWNLOADURL }}"
            --build-arg V2RAY_TARGETPLATFORM="${{ vars.V2RAY_TARGETPLATFORM }}"
            --build-arg V2RAY_TAG="${{ vars.V2RAY_TAG }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/ssrfargateqin

      - uses: actions/checkout@v3
      - name: Refresh Server
        run: python3 ECSManager.py